# Week 5 Assignment - Where to Open A New Restaurant in Kirkland

## I. Description of The Problem And Discussion of The Background

####       Kirkland is a city in western Washington with a population of about 93,000 according to 2019 census report. It is adjacent to Bellevue and Redmond, where many big companies such as Expedia, and Microsoft locate. And is about 20 minutes drive from Seattle downtown. Kirkland has beautiful waterfront areas, numerous parks,  and several art galleries. It has attracted more and more people to move in and live there. According to World Population Review, in the past decade, its population has grown by 88.47% and is continuing to grow at a current rate of 1.32% each year. Hence, there is a growing need for leisure, such as entertainment and dining.

#### This report will use Python segmenting and clustering techniques to fetch venue data from Foursquare to locate an area which will be ideal for someone to open a new restaurant in Kirkland. It will not consider other factors that generally impact such decisions, like cuisine preferences and average spending of targeted customers, rent cost, etc..

## II. Data Used in The Report

#### In this report, I will use neighborhood information from kirklandwa.org for clustering and segmentation, and the venue information from Foursquare to analyze each neighborhood to find the ideal area to open this new restaurant.

## III. Methodology

#### Due to the fact that Kirkland is a small city, there isn't any readily usable open source data online, I will have to create a dataframe with the neighborhood data obtained from kirklandwa.org, using Python.

In [97]:
# Create pandas dataframe from lists of lists
import pandas as pd
data= [[98034, 'Finn hill, Kirkland, WA'], [98034, 'Juanita, Kirkland, WA'], [98034, 'Kingsgate, Kirkland, WA'], [98034, 'Totem Lake, Kirkland, WA'], [98033, 'Market, Kirkland, WA'],
      [98033, 'Norkirk, Kirkland, WA'], [98033, 'Highlands, Kirkland, WA'], [98033, 'North Rose Hill, Kirkland'], [98033, 'Moss Bay, Kirkland, WA'], [98033, 'Everest, Kirkland, WA'], 
      [98033, 'South Rose Hill, Kirkland'], [98033, 'Bridle Trails, Kirkland, WA'], [98033, 'Lakeview, Kirkland, WA'], [98033, 'Central Houghton, Kirkland, WA']]
      
df=pd.DataFrame(data, columns= ['Zipcode', 'Neighborhood'])
df

    Zipcode                    Neighborhood
0     98034         Finn hill, Kirkland, WA
1     98034           Juanita, Kirkland, WA
2     98034         Kingsgate, Kirkland, WA
3     98034        Totem Lake, Kirkland, WA
4     98033            Market, Kirkland, WA
5     98033           Norkirk, Kirkland, WA
6     98033         Highlands, Kirkland, WA
7     98033       North Rose Hill, Kirkland
8     98033          Moss Bay, Kirkland, WA
9     98033           Everest, Kirkland, WA
10    98033       South Rose Hill, Kirkland
11    98033     Bridle Trails, Kirkland, WA
12    98033          Lakeview, Kirkland, WA
13    98033  Central Houghton, Kirkland, WA

#### Now that the dataframe is created, I will create a second dataframe of coordinates to combine it with the first one, using Geocoder Python package.

In [98]:
import numpy as np
import requests
!conda install -c conda-forge geopy --yes
from geopy.geocoders import Nominatim

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

In [99]:
! pip install geocoder
import geocoder

Requirement already satisfied: geocoder in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (1.38.1)
Requirement already satisfied: click in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (7.1.2)
Requirement already satisfied: six in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (1.15.0)
Requirement already satisfied: requests in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (2.24.0)
Requirement already satisfied: ratelim in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (0.1.6)
Requirement already satisfied: future in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (0.18.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests->geocoder) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests->geocoder) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests->geocoder) (2.10)
Requirement already satisfied: decorator in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from ratelim->geocoder) (4.4.2)

In [100]:
addresses = df['Neighborhood']
geolocator = Nominatim(user_agent="kirkland_explorer")
Latitude=[]
Longitude=[]

for address in addresses:
    
    location = geolocator.geocode(address)
    latitude = location.latitude
    longitude = location.longitude
    Latitude.append(latitude)
    Longitude.append(longitude)
    print('The geographical coordinates of {} are {}, {}'.format(address, latitude, longitude))

print(Latitude, Longitude)

The geographical coordinates of Finn hill, Kirkland, WA are 47.7173206, -122.2273471
The geographical coordinates of Juanita, Kirkland, WA are 47.7031543, -122.2070689
The geographical coordinates of Kingsgate, Kirkland, WA are 47.7273256, -122.1797584
The geographical coordinates of Totem Lake, Kirkland, WA are 47.71085465, -122.17601716707459
The geographical coordinates of Market, Kirkland, WA are 47.6859573, -122.1920249
The geographical coordinates of Norkirk, Kirkland, WA are 47.6901157, -122.2004116
The geographical coordinates of Highlands, Kirkland, WA are 47.7437086, -122.3695739
The geographical coordinates of North Rose Hill, Kirkland are 40.743338, -73.9841594
The geographical coordinates of Moss Bay, Kirkland, WA are 47.6720432, -122.2067908
The geographical coordinates of Everest, Kirkland, WA are 47.6709584, -122.1909832
The geographical coordinates of South Rose Hill, Kirkland are 47.6762254, -122.1690858
The geographical coordinates of Bridle Trails, Kirkland, WA are 47.6658799, -122.1653646624213
The geographical coordinates of Lakeview, Kirkland, WA are 47.376322, -119.50450371427928
The geographical coordinates of Central Houghton, Kirkland, WA are 47.6609322, -122.2059572
[47.7173206, 47.7031543, 47.7273256, 47.71085465, 47.6859573, 47.6901157, 47.7437086, 40.743338, 47.6720432, 47.6709584, 47.6762254, 47.6658799, 47.376322, 47.6609322] [-122.2273471, -122.2070689, -122.1797584, -122.17601716707459, -122.1920249, -122.2004116, -122.3695739, -73.9841594, -122.2067908, -122.1909832, -122.1690858, -122.1653646624213, -119.50450371427928, -122.2059572]

In [101]:
# Get the coordinates into a dataframe
df['Latitude']=Latitude
df['Longitude']=Longitude
df

    Zipcode                    Neighborhood   Latitude   Longitude
0     98034         Finn hill, Kirkland, WA  47.717321 -122.227347
1     98034           Juanita, Kirkland, WA  47.703154 -122.207069
2     98034         Kingsgate, Kirkland, WA  47.727326 -122.179758
3     98034        Totem Lake, Kirkland, WA  47.710855 -122.176017
4     98033            Market, Kirkland, WA  47.685957 -122.192025
5     98033           Norkirk, Kirkland, WA  47.690116 -122.200412
6     98033         Highlands, Kirkland, WA  47.743709 -122.369574
7     98033       North Rose Hill, Kirkland  40.743338  -73.984159
8     98033          Moss Bay, Kirkland, WA  47.672043 -122.206791
9     98033           Everest, Kirkland, WA  47.670958 -122.190983
10    98033       South Rose Hill, Kirkland  47.676225 -122.169086
11    98033     Bridle Trails, Kirkland, WA  47.665880 -122.165365
12    98033          Lakeview, Kirkland, WA  47.376322 -119.504504
13    98033  Central Houghton, Kirkland, WA  47.660932 -122.205957

In [102]:
#manually update the wrong coordinates using the correct ones found from google
df.at[7,'Latitude']=47.6932
df.at[7,'Longitude']=122.1703
df.at[12, 'Longitude']= 122.2060
df.at[12,'Latitude']= 47.6769
df.at[6, 'Latitude']= 47.6896
df.at[6, 'Longitude'] = 122.186
df

    Zipcode                    Neighborhood   Latitude   Longitude
0     98034         Finn hill, Kirkland, WA  47.717321 -122.227347
1     98034           Juanita, Kirkland, WA  47.703154 -122.207069
2     98034         Kingsgate, Kirkland, WA  47.727326 -122.179758
3     98034        Totem Lake, Kirkland, WA  47.710855 -122.176017
4     98033            Market, Kirkland, WA  47.685957 -122.192025
5     98033           Norkirk, Kirkland, WA  47.690116 -122.200412
6     98033         Highlands, Kirkland, WA  47.689600  122.186000
7     98033       North Rose Hill, Kirkland  47.693200  122.170300
8     98033          Moss Bay, Kirkland, WA  47.672043 -122.206791
9     98033           Everest, Kirkland, WA  47.670958 -122.190983
10    98033       South Rose Hill, Kirkland  47.676225 -122.169086
11    98033     Bridle Trails, Kirkland, WA  47.665880 -122.165365
12    98033          Lakeview, Kirkland, WA  47.676900  122.206000
13    98033  Central Houghton, Kirkland, WA  47.660932 -122.205957

In [103]:
df.shape

(14, 4)

#### Now that we have all the neighborhood information of Kirkland, we can start explore the city of Kirkland by creating a map of Kirkland and obtaining venue information of it from Foursquare.

In [104]:
# import libraries
import matplotlib.cm as cm
import matplotlib.colors as colors

from sklearn.cluster import KMeans

!conda install -c conda-forge folium=0.5.0 --yes 
import folium 

print('Libraries imported.')

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Libraries imported.

#### After importing needed libraries, I will use geopy library to get coordinates of Kirkland.

In [105]:
city = 'Kirkland, Washington, USA'

geolocator = Nominatim(user_agent="kirkland_explorer")
location1 = geolocator.geocode(city)
lat = location1.latitude
lng = location1.longitude
print('The geograpical coordinate of Kirkland, WA are {}, {}.'.format(lat, lng))

The geograpical coordinate of Kirkland, WA are 47.6859573, -122.1920249.

In [106]:
# Create the map of Kirkland
map_kirkland = folium.Map(location=[lat, lng], zoom_start=10)

for lat, lng, zipcode, neighborhood in zip(df['Latitude'], df['Longitude'], df['Zipcode'], df['Neighborhood']):
    label = '{}, {}'.format(neighborhood, zipcode)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_kirkland)  
    
map_kirkland

In [107]:
# Define Foursquare credentials and version
CLIENT_ID = 'XXXXXXXXXXXXXE' 
CLIENT_SECRET = 'XXXXXXXXXXXX0' 
VERSION = '20200708'

In [108]:
# Explore Neighborhoods in Kirkland
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng)
            
        results = requests.get(url).json()['response']['groups'][0]['items']
        
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [109]:
kirkland_venues = getNearbyVenues(names=df['Neighborhood'],
                                   latitudes=df['Latitude'],
                                   longitudes=df['Longitude']
                                  )

Finn hill, Kirkland, WA
Juanita, Kirkland, WA
Kingsgate, Kirkland, WA
Totem Lake, Kirkland, WA
Market, Kirkland, WA
Norkirk, Kirkland, WA
Highlands, Kirkland, WA
North Rose Hill, Kirkland
Moss Bay, Kirkland, WA
Everest, Kirkland, WA
South Rose Hill, Kirkland
Bridle Trails, Kirkland, WA
Lakeview, Kirkland, WA
Central Houghton, Kirkland, WA

In [110]:
print(kirkland_venues.shape)
kirkland_venues.head()

(330, 7)

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,"Finn hill, Kirkland, WA",47.717321,-122.227347,Juanita Beach Park,47.704708,-122.215304,Park
1,"Finn hill, Kirkland, WA",47.717321,-122.227347,Cafe Juanita,47.707618,-122.212426,Italian Restaurant
2,"Finn hill, Kirkland, WA",47.717321,-122.227347,Bala Yoga,47.707220,-122.211075,Yoga Studio
3,"Finn hill, Kirkland, WA",47.717321,-122.227347,Urban Coffee Lounge,47.707020,-122.211462,Coffee Shop
4,"Finn hill, Kirkland, WA",47.717321,-122.227347,"Columbia Athletic Clubs, Juanita Bay",47.703480,-122.209650,Gym / Fitness Center

In [111]:
kirkland_venues.groupby('Neighborhood').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
"Bridle Trails, Kirkland, WA",30,30,30,30,30,30
"Central Houghton, Kirkland, WA",30,30,30,30,30,30
"Everest, Kirkland, WA",30,30,30,30,30,30
"Finn hill, Kirkland, WA",30,30,30,30,30,30
"Juanita, Kirkland, WA",30,30,30,30,30,30
"Kingsgate, Kirkland, WA",30,30,30,30,30,30
"Market, Kirkland, WA",30,30,30,30,30,30
"Moss Bay, Kirkland, WA",30,30,30,30,30,30
"Norkirk, Kirkland, WA",30,30,30,30,30,30
"South Rose Hill, Kirkland",30,30,30,30,30,30
"Totem Lake, Kirkland, WA",30,30,30,30,30,30

In [112]:
print('There are {} uniques categories.'.format(len(kirkland_venues['Venue Category'].unique())))

There are 76 uniques categories.

In [113]:
# Analyze each neighborhood
kirkland_onehot = pd.get_dummies(kirkland_venues[['Venue Category']], prefix="", prefix_sep="")

kirkland_onehot['Neighborhood'] = kirkland_venues['Neighborhood'] 

fixed_columns = [kirkland_onehot.columns[-1]] + list(kirkland_onehot.columns[:-1])
kirkland_onehot = kirkland_onehot[fixed_columns]

kirkland_onehot.head()

,Neighborhood,American Restaurant,Amphitheater,Asian Restaurant,Badminton Court,Bar,Baseball Field,Bay,Beach,Beer Bar,...,Theater,Trail,Turkish Restaurant,Vineyard,Warehouse Store,Waterfront,Wine Bar,Wine Shop,Winery,Yoga Studio
0,"Finn hill, Kirkland, WA",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"Finn hill, Kirkland, WA",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"Finn hill, Kirkland, WA",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,"Finn hill, Kirkland, WA",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"Finn hill, Kirkland, WA",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [114]:
kirkland_onehot.shape

(330, 77)

In [115]:
# Group rows by neighborhood and by taking the mean of the frequency of occurrence of each category
kirkland_grouped = kirkland_onehot.groupby('Neighborhood').mean().reset_index()
kirkland_grouped

,Neighborhood,American Restaurant,Amphitheater,Asian Restaurant,Badminton Court,Bar,Baseball Field,Bay,Beach,Beer Bar,...,Theater,Trail,Turkish Restaurant,Vineyard,Warehouse Store,Waterfront,Wine Bar,Wine Shop,Winery,Yoga Studio
0,"Bridle Trails, Kirkland, WA",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.033333,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.033333
1,"Central Houghton, Kirkland, WA",0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.066667,0.033333,...,0.000000,0.000000,0.033333,0.000000,0.000000,0.033333,0.033333,0.033333,0.000000,0.000000
2,"Everest, Kirkland, WA",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.066667,0.033333,...,0.000000,0.033333,0.033333,0.000000,0.000000,0.033333,0.000000,0.033333,0.000000,0.000000
3,"Finn hill, Kirkland, WA",0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.033333,0.033333,0.000000,...,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333
4,"Juanita, Kirkland, WA",0.000000,0.000000,0.033333,0.033333,0.033333,0.033333,0.033333,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333
5,"Kingsgate, Kirkland, WA",0.033333,0.033333,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.033333,0.000000,0.133333,0.000000
6,"Market, Kirkland, WA",0.000000,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.033333,0.033333,...,0.000000,0.033333,0.033333,0.000000,0.033333,0.033333,0.000000,0.033333,0.000000,0.000000
7,"Moss Bay, Kirkland, WA",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.066667,0.033333,...,0.000000,0.000000,0.033333,0.000000,0.000000,0.033333,0.000000,0.033333,0.000000,0.000000
8,"Norkirk, Kirkland, WA",0.000000,0.000000,0.000000,0.000000,0.000000,0.033333,0.033333,0.033333,0.033333,...,0.000000,0.033333,0.033333,0.000000,0.000000,0.033333,0.000000,0.033333,0.000000,0.033333
9,"South Rose Hill, Kirkland",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.033333,0.000000,0.000000,0.033333,0.033333,0.000000,0.000000,0.000000,0.000000
10,"Totem Lake, Kirkland, WA",0.000000,0.000000,0.066667,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000

In [116]:
kirkland_grouped.shape

(11, 77)

In [117]:
# Print each neighborhood along with the top 5 most common venues

num_top_venues = 5

for hood in kirkland_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = kirkland_grouped[kirkland_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Bridle Trails, Kirkland, WA----
                 venue  freq
0          Coffee Shop  0.10
1                 Park  0.10
2  Japanese Restaurant  0.07
3          Pizza Place  0.07
4                  Gym  0.03


----Central Houghton, Kirkland, WA----
            venue  freq
0            Park  0.07
1           Beach  0.07
2           Hotel  0.07
3  Sandwich Place  0.07
4    Burger Joint  0.07


----Everest, Kirkland, WA----
            venue  freq
0            Park  0.07
1  Sandwich Place  0.07
2           Beach  0.07
3    Optical Shop  0.03
4  Ice Cream Shop  0.03


----Finn hill, Kirkland, WA----
                      venue  freq
0               Coffee Shop  0.10
1          Sushi Restaurant  0.10
2                      Park  0.10
3               Yoga Studio  0.03
4  Mediterranean Restaurant  0.03


----Juanita, Kirkland, WA----
                      venue  freq
0               Coffee Shop  0.13
1                      Park  0.10
2          Sushi Restaurant  0.10
3         Indian Restaurant  0.07
4  Mediterranean Restaurant  0.03


----Kingsgate, Kirkland, WA----
                 venue  freq
0               Winery  0.13
1          Coffee Shop  0.10
2        Grocery Store  0.07
3  American Restaurant  0.03
4            Pet Store  0.03


----Market, Kirkland, WA----
             venue  freq
0             Park  0.07
1   Sandwich Place  0.07
2  Thai Restaurant  0.03
3      Coffee Shop  0.03
4            Hotel  0.03


----Moss Bay, Kirkland, WA----
                venue  freq
0                Park  0.07
1               Beach  0.07
2      Sandwich Place  0.07
3         Coffee Shop  0.07
4  Mexican Restaurant  0.03


----Norkirk, Kirkland, WA----
                  venue  freq
0                  Park  0.10
1        Sandwich Place  0.07
2           Yoga Studio  0.03
3                 Trail  0.03
4  Gym / Fitness Center  0.03


----South Rose Hill, Kirkland----
             venue  freq
0      Coffee Shop  0.07
1       Playground  0.07
2             Park  0.07
3      Pizza Place  0.07
4  Thai Restaurant  0.03


----Totem Lake, Kirkland, WA----
                 venue  freq
0          Coffee Shop  0.10
1     Asian Restaurant  0.07
2        Grocery Store  0.07
3  Japanese Restaurant  0.07
4           Food Truck  0.03

In [118]:
# create a dataframe with above data
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [119]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = kirkland_grouped['Neighborhood']

for ind in np.arange(kirkland_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(kirkland_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,"Bridle Trails, Kirkland, WA",Park,Coffee Shop,Japanese Restaurant,Pizza Place,Gym,Playground,Organic Grocery,Optical Shop,Knitting Store,Grocery Store
1,"Central Houghton, Kirkland, WA",Sandwich Place,Hotel,Park,Beach,Burger Joint,American Restaurant,Ice Cream Shop,Grocery Store,Irish Pub,Greek Restaurant
2,"Everest, Kirkland, WA",Beach,Park,Sandwich Place,Playground,Organic Grocery,Burger Joint,Café,Grocery Store,Chinese Restaurant,Coffee Shop
3,"Finn hill, Kirkland, WA",Coffee Shop,Park,Sushi Restaurant,Shoe Repair,Italian Restaurant,Gym / Fitness Center,Gym,Grocery Store,Greek Restaurant,Mediterranean Restaurant
4,"Juanita, Kirkland, WA",Coffee Shop,Park,Sushi Restaurant,Indian Restaurant,Shoe Repair,Italian Restaurant,Harbor / Marina,Gym / Fitness Center,Grocery Store,Mediterranean Restaurant
5,"Kingsgate, Kirkland, WA",Winery,Coffee Shop,Grocery Store,Japanese Restaurant,Pharmacy,Pet Store,New American Restaurant,Mediterranean Restaurant,Karaoke Bar,Italian Restaurant
6,"Market, Kirkland, WA",Park,Sandwich Place,Playground,Sports Bar,Mexican Restaurant,Coffee Shop,Optical Shop,Dessert Shop,Café,Burger Joint
7,"Moss Bay, Kirkland, WA",Sandwich Place,Coffee Shop,Beach,Park,Playground,Chinese Restaurant,Persian Restaurant,Organic Grocery,Dessert Shop,Mexican Restaurant
8,"Norkirk, Kirkland, WA",Park,Sandwich Place,Yoga Studio,Burger Joint,Harbor / Marina,Hotel,Ice Cream Shop,Greek Restaurant,Italian Restaurant,French Restaurant
9,"South Rose Hill, Kirkland",Pizza Place,Playground,Park,Coffee Shop,Waterfront,Warehouse Store,Mexican Restaurant,Knitting Store,Optical Shop,Organic Grocery
10,"Totem Lake, Kirkland, WA",Coffee Shop,Japanese Restaurant,Asian Restaurant,Grocery Store,Brewery,Pet Store,Cosmetics Shop,Comic Shop,Clothing Store,Mediterranean Restaurant

In [120]:
# since there are only 11 neighborhoods have venue information pulled from Foursquare, before merging the venue information with the 
# previous dataframe, i will need to remove corresponding neighborhoods from previous dataframe
df.drop(df.index[[6,7]], inplace=True)
df

    Zipcode                    Neighborhood   Latitude   Longitude
0     98034         Finn hill, Kirkland, WA  47.717321 -122.227347
1     98034           Juanita, Kirkland, WA  47.703154 -122.207069
2     98034         Kingsgate, Kirkland, WA  47.727326 -122.179758
3     98034        Totem Lake, Kirkland, WA  47.710855 -122.176017
4     98033            Market, Kirkland, WA  47.685957 -122.192025
5     98033           Norkirk, Kirkland, WA  47.690116 -122.200412
8     98033          Moss Bay, Kirkland, WA  47.672043 -122.206791
9     98033           Everest, Kirkland, WA  47.670958 -122.190983
10    98033       South Rose Hill, Kirkland  47.676225 -122.169086
11    98033     Bridle Trails, Kirkland, WA  47.665880 -122.165365
12    98033          Lakeview, Kirkland, WA  47.676900  122.206000
13    98033  Central Houghton, Kirkland, WA  47.660932 -122.205957

In [121]:
# drop one more neighborhood
df.drop(df.index[10], inplace=True)
df

    Zipcode                    Neighborhood   Latitude   Longitude
0     98034         Finn hill, Kirkland, WA  47.717321 -122.227347
1     98034           Juanita, Kirkland, WA  47.703154 -122.207069
2     98034         Kingsgate, Kirkland, WA  47.727326 -122.179758
3     98034        Totem Lake, Kirkland, WA  47.710855 -122.176017
4     98033            Market, Kirkland, WA  47.685957 -122.192025
5     98033           Norkirk, Kirkland, WA  47.690116 -122.200412
8     98033          Moss Bay, Kirkland, WA  47.672043 -122.206791
9     98033           Everest, Kirkland, WA  47.670958 -122.190983
10    98033       South Rose Hill, Kirkland  47.676225 -122.169086
11    98033     Bridle Trails, Kirkland, WA  47.665880 -122.165365
13    98033  Central Houghton, Kirkland, WA  47.660932 -122.205957

In [124]:
# reset index of df
df.reset_index(drop=True, inplace=True)
df

    Zipcode                    Neighborhood   Latitude   Longitude
0     98034         Finn hill, Kirkland, WA  47.717321 -122.227347
1     98034           Juanita, Kirkland, WA  47.703154 -122.207069
2     98034         Kingsgate, Kirkland, WA  47.727326 -122.179758
3     98034        Totem Lake, Kirkland, WA  47.710855 -122.176017
4     98033            Market, Kirkland, WA  47.685957 -122.192025
5     98033           Norkirk, Kirkland, WA  47.690116 -122.200412
6     98033          Moss Bay, Kirkland, WA  47.672043 -122.206791
7     98033           Everest, Kirkland, WA  47.670958 -122.190983
8     98033       South Rose Hill, Kirkland  47.676225 -122.169086
9     98033     Bridle Trails, Kirkland, WA  47.665880 -122.165365
10    98033  Central Houghton, Kirkland, WA  47.660932 -122.205957

In [125]:
# cluster neighborhoods
kclusters = 3

kirkland_grouped_clustering = kirkland_grouped.drop('Neighborhood', 1)

kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(kirkland_grouped_clustering)

kmeans.labels_[0:10]

array([2, 1, 1, 0, 0, 0, 1, 1, 1, 2], dtype=int32)

In [126]:
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

In [127]:
kirkland_merged = df

kirkland_merged = kirkland_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

kirkland_merged

,Zipcode,Neighborhood,Latitude,Longitude,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,98034,"Finn hill, Kirkland, WA",47.717321,-122.227347,0,Coffee Shop,Park,Sushi Restaurant,Shoe Repair,Italian Restaurant,Gym / Fitness Center,Gym,Grocery Store,Greek Restaurant,Mediterranean Restaurant
1,98034,"Juanita, Kirkland, WA",47.703154,-122.207069,0,Coffee Shop,Park,Sushi Restaurant,Indian Restaurant,Shoe Repair,Italian Restaurant,Harbor / Marina,Gym / Fitness Center,Grocery Store,Mediterranean Restaurant
2,98034,"Kingsgate, Kirkland, WA",47.727326,-122.179758,0,Winery,Coffee Shop,Grocery Store,Japanese Restaurant,Pharmacy,Pet Store,New American Restaurant,Mediterranean Restaurant,Karaoke Bar,Italian Restaurant
3,98034,"Totem Lake, Kirkland, WA",47.710855,-122.176017,0,Coffee Shop,Japanese Restaurant,Asian Restaurant,Grocery Store,Brewery,Pet Store,Cosmetics Shop,Comic Shop,Clothing Store,Mediterranean Restaurant
4,98033,"Market, Kirkland, WA",47.685957,-122.192025,1,Park,Sandwich Place,Playground,Sports Bar,Mexican Restaurant,Coffee Shop,Optical Shop,Dessert Shop,Café,Burger Joint
5,98033,"Norkirk, Kirkland, WA",47.690116,-122.200412,1,Park,Sandwich Place,Yoga Studio,Burger Joint,Harbor / Marina,Hotel,Ice Cream Shop,Greek Restaurant,Italian Restaurant,French Restaurant
6,98033,"Moss Bay, Kirkland, WA",47.672043,-122.206791,1,Sandwich Place,Coffee Shop,Beach,Park,Playground,Chinese Restaurant,Persian Restaurant,Organic Grocery,Dessert Shop,Mexican Restaurant
7,98033,"Everest, Kirkland, WA",47.670958,-122.190983,1,Beach,Park,Sandwich Place,Playground,Organic Grocery,Burger Joint,Café,Grocery Store,Chinese Restaurant,Coffee Shop
8,98033,"South Rose Hill, Kirkland",47.676225,-122.169086,2,Pizza Place,Playground,Park,Coffee Shop,Waterfront,Warehouse Store,Mexican Restaurant,Knitting Store,Optical Shop,Organic Grocery
9,98033,"Bridle Trails, Kirkland, WA",47.665880,-122.165365,2,Park,Coffee Shop,Japanese Restaurant,Pizza Place,Gym,Playground,Organic Grocery,Optical Shop,Knitting Store,Grocery Store
10,98033,"Central Houghton, Kirkland, WA",47.660932,-122.205957,1,Sandwich Place,Hotel,Park,Beach,Burger Joint,American Restaurant,Ice Cream Shop,Grocery Store,Irish Pub,Greek Restaurant

In [128]:
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

markers_colors = []
for lat, lon, poi, cluster in zip(kirkland_merged['Latitude'], kirkland_merged['Longitude'], kirkland_merged['Neighborhood'], kirkland_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

In [129]:
# Examine Each Cluster
# Cluster 1
kirkland_merged.loc[kirkland_merged['Cluster Labels'] == 0, kirkland_merged.columns[[1] + list(range(5, kirkland_merged.shape[1]))]]

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,"Finn hill, Kirkland, WA",Coffee Shop,Park,Sushi Restaurant,Shoe Repair,Italian Restaurant,Gym / Fitness Center,Gym,Grocery Store,Greek Restaurant,Mediterranean Restaurant
1,"Juanita, Kirkland, WA",Coffee Shop,Park,Sushi Restaurant,Indian Restaurant,Shoe Repair,Italian Restaurant,Harbor / Marina,Gym / Fitness Center,Grocery Store,Mediterranean Restaurant
2,"Kingsgate, Kirkland, WA",Winery,Coffee Shop,Grocery Store,Japanese Restaurant,Pharmacy,Pet Store,New American Restaurant,Mediterranean Restaurant,Karaoke Bar,Italian Restaurant
3,"Totem Lake, Kirkland, WA",Coffee Shop,Japanese Restaurant,Asian Restaurant,Grocery Store,Brewery,Pet Store,Cosmetics Shop,Comic Shop,Clothing Store,Mediterranean Restaurant

In [132]:
print('Cluster 1 is popular for family leisure and dining.')

Cluster 1 is popular for family leisure and dining.

In [131]:
# Cluster 2
kirkland_merged.loc[kirkland_merged['Cluster Labels'] == 1, kirkland_merged.columns[[1] + list(range(5, kirkland_merged.shape[1]))]]

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
4,"Market, Kirkland, WA",Park,Sandwich Place,Playground,Sports Bar,Mexican Restaurant,Coffee Shop,Optical Shop,Dessert Shop,Café,Burger Joint
5,"Norkirk, Kirkland, WA",Park,Sandwich Place,Yoga Studio,Burger Joint,Harbor / Marina,Hotel,Ice Cream Shop,Greek Restaurant,Italian Restaurant,French Restaurant
6,"Moss Bay, Kirkland, WA",Sandwich Place,Coffee Shop,Beach,Park,Playground,Chinese Restaurant,Persian Restaurant,Organic Grocery,Dessert Shop,Mexican Restaurant
7,"Everest, Kirkland, WA",Beach,Park,Sandwich Place,Playground,Organic Grocery,Burger Joint,Café,Grocery Store,Chinese Restaurant,Coffee Shop
10,"Central Houghton, Kirkland, WA",Sandwich Place,Hotel,Park,Beach,Burger Joint,American Restaurant,Ice Cream Shop,Grocery Store,Irish Pub,Greek Restaurant

In [133]:
print('Cluster 2 is popular for family leisure and fastfood.')

Cluster 2 is popular for family leisure and fastfood.

In [134]:
# Cluster 3
kirkland_merged.loc[kirkland_merged['Cluster Labels'] == 2, kirkland_merged.columns[[1] + list(range(5, kirkland_merged.shape[1]))]]

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
8,"South Rose Hill, Kirkland",Pizza Place,Playground,Park,Coffee Shop,Waterfront,Warehouse Store,Mexican Restaurant,Knitting Store,Optical Shop,Organic Grocery
9,"Bridle Trails, Kirkland, WA",Park,Coffee Shop,Japanese Restaurant,Pizza Place,Gym,Playground,Organic Grocery,Optical Shop,Knitting Store,Grocery Store

In [135]:
print('Cluster 3 is popular for family leisure and fastfood.')

Cluster 3 is popular for family leisure and fastfood.

## IV. Results

#### From the above analysis of neighborhoods in kirkland, each cluster has its unique characteristics.  Cluster 1 is popular for family leisure and dining. Cluster 2 is popular for family leisure and fastfood. Cluster 3 is popular for family leisure, fast food and errands.

## V. Discussion

####  All three clusters have parks to attract families to spend time in the area, especially during weekends and holidays. But each cluster also has other unique characteristics to offer. Cluster 1 has more table service dining options, which is a go-to area for meals. This guarantees a certain amount of potential customers for any new restaurants as it helps the exposure of the existence of a new restaurant. Cluster 2 seems to have more fast food options.Similar to Cluster 1, Cluster 3 also has more fast food option than table service restaurants.

## VI. Conclusion

#### Based on the each clusters' characteristics in kirkland, it's ideal to open the new restaurant in cluster 1 area.